config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  devise_for :users

  resources :events do
    resources :e_comments
  end

  resources :meets do
    resources :m_comments
  end

  resources :communities, only: [ :index, :show ]

  resources :mailers, only: [ :create ]

  namespace :admin do
    resources :programs
    resources :faculties
    resources :communities, except: [ :index, :show ]
    resources :events, only: [ :create, :update ]
    resources :mailers
  end

  namespace :api, format: "json" do
    namespace :v1 do
      resources :events, only: [ :index, :show ]
      resources :meets, only: [ :index, :show ]
      resources :faculties, only: [ :index, :show ]
      resources :communities, only: [ :index, :show ]
    end
  end

  get "welcome/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  get "welcome/index"
  get "welcome/about"

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:

    can :create, Mailer

    return unless user.present?
    can :read, Event.all
    can :read, Meet.all
    can :manage, Event, user: user
    can :manage, Meet, user: user
    can :read, Community
    can :manage, EComment, user: user
    can :manage, MComment, user: user

    return unless user.role == "admin"
    can :read, :all
    can :manage, :all

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    # can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/community.rb
class Community < ApplicationRecord
  has_many :events
end

app/models/e_comment.rb
class EComment < ApplicationRecord
  belongs_to :event
  belongs_to :user

  after_create_commit { broadcast_prepend_to("e_comments") }

  default_scope { order(created_at: :desc) }
end

app/models/event.rb
class Event < ApplicationRecord
    validates :title, presence: true, length: { minimum: 5 }
    belongs_to :user
    belongs_to :community
    has_many :e_comments, dependent: :destroy
    mount_uploader :event_image, EventImageUploader
end

app/models/faculty.rb
class Faculty < ApplicationRecord
  has_many :programs
end

app/models/m_comment.rb
class MComment < ApplicationRecord
  belongs_to :meet
  belongs_to :user

  after_create_commit { broadcast_prepend_to("e_meets") }
end

app/models/mailer.rb
class Mailer < ApplicationRecord
  validates :email, presence: true
end

app/models/meet.rb
class Meet < ApplicationRecord
  belongs_to :user
  has_many :m_comments, dependent: :destroy
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/program.rb
class Program < ApplicationRecord
  belongs_to :faculty
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events
  has_many :e_comments

  has_many :meets
  has_many :m_comments

  has_one :profile
  after_create :create_profile
end

app/controllers/e_comments_controller.rb
class ECommentsController < ApplicationController
  before_action :set_e_comment, only: %i[ show edit update destroy ]

  def index
    @e_comments = EComment.all
  end

  def show
  end

  def new
    @e_comment = EComment.new
  end

  def edit
  end

  def create
    @e_comment = current_user.e_comments.new(e_comment_params)
    @event = Event.find(params[:event_id])

    respond_to do |format|
      if @e_comment.save
        format.html { redirect_to @e_comment.event, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @e_comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @e_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @e_comment.update(e_comment_params)
        format.html { redirect_to @e_comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @e_comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @e_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @e_comment.destroy!

    respond_to do |format|
      format.html { redirect_to @e_comment.event, status: :see_other, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_e_comment
      @e_comment = EComment.find(params[:id])
    end

    def e_comment_params
      params.require(:e_comment).permit(:body).merge(event_id: params[:event_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/e_comments_helper.rb
module ECommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/m_comments_helper.rb
module MCommentsHelper
end

app/helpers/mailers_helper.rb
module MailersHelper
end

app/helpers/meets_helper.rb
module MeetsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/e_comments/_e_comment.html.erb
<div class="e_comment_block">
  <h2><%= e_comment.user.username %></h2>
  <p><%= e_comment.body %></p>
  <%# if can? :manage, e_comment %>
    <%= link_to "Destroy e_Comment", [ e_comment.event, e_comment], data: { turbo_stream: false, turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
  <%# end %>
</div>

app/views/e_comments/_form.html.erb
<% e_comment = EComment.new %>

<%= form_with(model: [@event, e_comment]) do |form| %>
  <% if e_comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(e_comment.errors.count, "error") %> prohibited this e_comment from being saved:</h2>

      <ul>
        <% e_comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/e_comments/edit.html.erb
<% content_for :title, "Editing comment" %>

<h1>Editing comment</h1>

<%= render "form", e_comment: @e_comment %>

<br>

<div>
  <%= link_to "Show this comment", @e_comment %> |
  <%= link_to "Back to comment", e_comments_path %>
</div>

app/views/e_comments/index.html.erb
<% content_for :title, "Comments" %>

<h1>Comments</h1>

<div id="comments">
  <% @e_comments.each do |e_comment| %>
    <%= render e_comment %>
    <p>
      <%= link_to "Show this comment", e_comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_e_comment_path %>

app/views/e_comments/new.html.erb
<% content_for :title, "New comment" %>

<h1>New comment</h1>

<%= render "form", e_comment: @e_comment %>

app/views/e_comments/show.html.erb
<%= render @e_comment %>

<div>
  <%= link_to "Edit this comment", edit_e_comment_path(@e_comment) %> |
  <%= link_to "Back to comments", e_comments_path %>

  <%= button_to "Destroy this comment", @e_comment, method: :delete %>
</div>