config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  devise_for :users

  resources :events do
    resources :e_comments
  end

  resources :meets do
    resources :m_comments
  end

  resources :communities, only: [ :index, :show ]

  resources :mailers, only: [ :create ]

  namespace :admin do
    resources :programs
    resources :faculties
    resources :communities, except: [ :index, :show ]
    resources :events, only: [ :create, :update ]
    resources :mailers
  end

  namespace :api, format: "json" do
    namespace :v1 do
      resources :events, only: [ :index, :show ]
      resources :meets, only: [ :index, :show ]
      resources :faculties, only: [ :index, :show ]
      resources :communities, only: [ :index, :show ]
    end
  end

  get "welcome/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  get "welcome/index"
  get "welcome/about"

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/faculty.rb
class Faculty < ApplicationRecord
  has_many :programs
end

app/controllers/admin/faculties_controller.rb
class Admin::FacultiesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_faculty, only: %i[ show edit update destroy ]

  # GET /faculties or /faculties.json
  def index
    if current_user.role == "admin"
      @faculties = Faculty.all
    end
  end

  # GET /faculties/1 or /faculties/1.json
  def show
  end

  # GET /faculties/new
  def new
    @faculty = Faculty.new
  end

  # GET /faculties/1/edit
  def edit
  end

  # POST /faculties or /faculties.json
  def create
    @faculty = Faculty.new(faculty_params)

    respond_to do |format|
      if @faculty.save
        format.html { redirect_to admin_faculty_path(@faculty), notice: "Faculty was successfully created." }
        format.json { render :show, status: :created, location: @faculty }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faculties/1 or /faculties/1.json
  def update
    respond_to do |format|
      if @faculty.update(faculty_params)
        format.html { redirect_to admin_faculty_path(@faculty), notice: "Faculty was successfully updated." }
        format.json { render :show, status: :ok, location: @faculty }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faculties/1 or /faculties/1.json
  def destroy
    @faculty.destroy!

    respond_to do |format|
      format.html { redirect_to admin_faculties_path, status: :see_other, notice: "Faculty was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faculty
      @faculty = Faculty.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def faculty_params
      params.require(:faculty).permit(:name)
    end
end

app/controllers/api/v1/faculties_controller.rb
class Api::V1::FacultiesController < ApplicationController
  def index
    @faculties = Faculty.all
  end

  def show
    @faculty = Faculty.find(params[:id])
  end
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_faculty, only: %i[ show edit update destroy ]

  # GET /faculties or /faculties.json
  def index
    @faculties = Faculty.all
  end

  # GET /faculties/1 or /faculties/1.json
  def show
  end

  # GET /faculties/new
  def new
    @faculty = Faculty.new
  end

  # GET /faculties/1/edit
  def edit
  end

  # POST /faculties or /faculties.json
  def create
    @faculty = Faculty.new(faculty_params)

    respond_to do |format|
      if @faculty.save
        format.html { redirect_to @faculty, notice: "Faculty was successfully created." }
        format.json { render :show, status: :created, location: @faculty }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faculties/1 or /faculties/1.json
  def update
    respond_to do |format|
      if @faculty.update(faculty_params)
        format.html { redirect_to @faculty, notice: "Faculty was successfully updated." }
        format.json { render :show, status: :ok, location: @faculty }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faculties/1 or /faculties/1.json
  def destroy
    @faculty.destroy!

    respond_to do |format|
      format.html { redirect_to faculties_path, status: :see_other, notice: "Faculty was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faculty
      @faculty = Faculty.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def faculty_params
      params.require(:faculty).permit(:name)
    end
end

app/helpers/api/v1/faculties_helper.rb
module Api::V1::FacultiesHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/views/admin/faculties/_faculty.html.erb
<div id="<%= dom_id faculty %>">
  <h2><%= faculty.name %></h2>
  <% faculty.programs.each do |program| %>
    <%= program.name %>
  <% end %>
</div>

app/views/admin/faculties/_form.html.erb
<%= form_with(model: [:admin, faculty]) do |form| %>
  <% if faculty.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(faculty.errors.count, "error") %> prohibited this faculty from being saved:</h2>

      <ul>
        <% faculty.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/faculties/edit.html.erb
<% content_for :title, "Editing faculty" %>

<h1>Editing faculty</h1>

<%= render "form", faculty: @faculty %>

<br>

<div>
  <%= link_to "Show this faculty", admin_faculty_path(@faculty) %> |
  <%= link_to "Back to faculties", admin_faculties_path %>
</div>

app/views/admin/faculties/index.html.erb
<% content_for :title, "Faculties" %>

<div class="O_BlockCardName">
  <div class="M_Header">
    <h1 class="page_title">Факультеты</h1>
    <%= link_to "Добавить факультет", new_admin_faculty_path, class: 'M_ButtonAdd'%>
  </div>
  <div id="faculties">
    <% @faculties.each do |faculty| %>
      <%= link_to admin_faculty_path(faculty), class: 'faculty_card' do %>
        <%= render faculty %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/admin/faculties/new.html.erb
<% content_for :title, "New faculty" %>

<h1>New faculty</h1>

<%= render "form", faculty: @faculty %>

<br>

<div>
  <%= link_to "Back to faculties", admin_faculties_path %>
</div>

app/views/admin/faculties/show.html.erb
<%= render @faculty %>


<div class="block_communities">
  <% @faculty.programs.each do |program| %>
    <%= link_to admin_program_path(program), class: "program_card" do %>
      <%= render program %>
    <% end%>
  <% end%>
</div>

<div>
  <%= link_to "Edit this faculty", edit_admin_faculty_path(@faculty) %> |
  <%= link_to "Back to faculties", admin_faculties_path %>

  <%= button_to "Destroy this faculty", admin_faculty_path(@faculty), method: :delete %>
</div>