config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  devise_for :users

  resources :events do
    resources :e_comments
  end

  resources :meets do
    resources :m_comments
  end

  resources :communities, only: [ :index, :show ]

  resources :mailers, only: [ :create ]

  namespace :admin do
    resources :programs
    resources :faculties
    resources :communities, except: [ :index, :show ]
    resources :events, only: [ :create, :update ]
    resources :mailers
  end

  namespace :api, format: "json" do
    namespace :v1 do
      resources :events, only: [ :index, :show ]
      resources :meets, only: [ :index, :show ]
      resources :faculties, only: [ :index, :show ]
      resources :communities, only: [ :index, :show ]
    end
  end

  get "welcome/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  get "welcome/index"
  get "welcome/about"

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:

    can :create, Mailer

    return unless user.present?
    can :read, Event.all
    can :read, Meet.all
    can :manage, Event, user: user
    can :manage, Meet, user: user
    can :read, Community
    can :manage, EComment, user: user
    can :manage, MComment, user: user

    return unless user.role == "admin"
    can :read, :all
    can :manage, :all

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    # can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/community.rb
class Community < ApplicationRecord
  has_many :events
end

app/models/e_comment.rb
class EComment < ApplicationRecord
  belongs_to :event
  belongs_to :user

  after_create_commit { broadcast_prepend_to("e_comments") }

  default_scope { order(created_at: :desc) }
end

app/models/event.rb
class Event < ApplicationRecord
    validates :title, presence: true, length: { minimum: 5 }
    belongs_to :user
    belongs_to :community
    has_many :e_comments, dependent: :destroy
    mount_uploader :event_image, EventImageUploader
end

app/models/faculty.rb
class Faculty < ApplicationRecord
  has_many :programs
end

app/models/m_comment.rb
class MComment < ApplicationRecord
  belongs_to :meet
  belongs_to :user

  after_create_commit { broadcast_prepend_to("e_meets") }
end

app/models/mailer.rb
class Mailer < ApplicationRecord
  validates :email, presence: true
end

app/models/meet.rb
class Meet < ApplicationRecord
  belongs_to :user
  has_many :m_comments, dependent: :destroy
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/program.rb
class Program < ApplicationRecord
  belongs_to :faculty
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events
  has_many :e_comments

  has_many :meets
  has_many :m_comments

  has_one :profile
  after_create :create_profile
end

app/controllers/api/v1/meets_controller.rb
class Api::V1::MeetsController < ApplicationController
  def index
    @meets = Meet.all
  end

  def show
    @meet = Meet.find(params[:id])
  end
end

app/controllers/meets_controller.rb
class MeetsController < ApplicationController
  before_action :set_meet, only: %i[ show edit update destroy ]

  # GET /meets or /meets.json
  def index
    @meets = Meet.all
  end

  # GET /meets/1 or /meets/1.json
  def show
  end

  # GET /meets/new
  def new
    @meet = Meet.new
  end

  # GET /meets/1/edit
  def edit
  end

  # POST /meets or /meets.json
  def create
    @meet = Meet.new(meet_params)

    respond_to do |format|
      if @meet.save
        format.html { redirect_to @meet, notice: "Meet was successfully created." }
        format.json { render :show, status: :created, location: @meet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meets/1 or /meets/1.json
  def update
    respond_to do |format|
      if @meet.update(meet_params)
        format.html { redirect_to @meet, notice: "Meet was successfully updated." }
        format.json { render :show, status: :ok, location: @meet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meets/1 or /meets/1.json
  def destroy
    @meet.destroy!

    respond_to do |format|
      format.html { redirect_to meets_path, status: :see_other, notice: "Meet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meet
      @meet = Meet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meet_params
      params.require(:meet).permit(:body, :date_hosted, :geotag, :user_id)
    end
end

app/helpers/api/v1/meets_helper.rb
module Api::V1::MeetsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/e_comments_helper.rb
module ECommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/m_comments_helper.rb
module MCommentsHelper
end

app/helpers/mailers_helper.rb
module MailersHelper
end

app/helpers/meets_helper.rb
module MeetsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/meets/_form.html.erb
<%= form_with(model: meet) do |form| %>
  <% if meet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(meet.errors.count, "error") %> prohibited this meet from being saved:</h2>

      <ul>
        <% meet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :date_hosted, style: "display: block" %>
    <%= form.datetime_field :date_hosted %>
  </div>

  <div>
    <%= form.label :geotag, style: "display: block" %>
    <%= form.text_field :geotag %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/meets/_meet.html.erb
<div id="<%= dom_id meet %>">
  <p>
    <strong>Body:</strong>
    <%= meet.body %>
  </p>

  <p>
    <strong>Date hosted:</strong>
    <%= meet.date_hosted %>
  </p>

  <p>
    <strong>Geotag:</strong>
    <%= meet.geotag %>
  </p>

  <p>
    <strong>User:</strong>
    <%= meet.user_id %>
  </p>

</div>

app/views/meets/edit.html.erb
<% content_for :title, "Editing meet" %>

<h1>Editing meet</h1>

<%= render "form", meet: @meet %>

<br>

<div>
  <%= link_to "Show this meet", @meet %> |
  <%= link_to "Back to meets", meets_path %>
</div>

app/views/meets/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Meets" %>

<h1>Meets</h1>

<div id="meets">
  <% @meets.each do |meet| %>
    <%= render meet %>
    <p>
      <%= link_to "Show this meet", meet %>
    </p>
  <% end %>
</div>

<%= link_to "New meet", new_meet_path %>

app/views/meets/new.html.erb
<% content_for :title, "New meet" %>

<h1>New meet</h1>

<%= render "form", meet: @meet %>

<br>

<div>
  <%= link_to "Back to meets", meets_path %>
</div>

app/views/meets/show.html.erb
<%= render @meet %>

<div>
  <%= link_to "Edit this meet", edit_meet_path(@meet) %> |
  <%= link_to "Back to meets", meets_path %>

  <%= button_to "Destroy this meet", @meet, method: :delete %>
</div>

<h2>Добавить комментарий:</h2>
<%= render "m_comments/form" %>

<%= turbo_stream_from "m_comments" %>

<h2>Комментарии</h2>
<%= turbo_frame_tag "m_comments" do %>
  <%= render @meet.m_comments %>
<% end %>